"""
Layer 9.2: Ask AgriBrain Q&A.
Handles user questions by routing to OpenRouter LLM with context.
"""

from typing import Dict, Any, List
import os
import json
import requests
from dotenv import load_dotenv

# Load Env
load_dotenv()

class QABot:
    
    def __init__(self):
        self.api_key = os.getenv("OPENROUTER_API_KEY")
        self.api_url = "https://openrouter.ai/api/v1/chat/completions"
        # User specified model
        self.model = "qwen/qwen3-vl-235b-a22b-thinking"
        
    def handle_query(self, query: str, context_snapshot: Dict[str, Any]) -> Dict[str, Any]:
        """
        Sends context + query to LLM for reasoning.
        """
        # Debug: Print Context Structure to Stderr
        # print(f"DEBUG CONTEXT: {json.dumps(context_snapshot, indent=2)}", file=os.sys.stderr)

        # 1. Prepare Prompt
        try:
            system_prompt = self._build_system_prompt(context_snapshot)
        except Exception as e:
            return self._fallback_response(f"Context Error: {str(e)}")
        
        # 2. Call LLM
        if not self.api_key:
            return self._fallback_response("Missing API Key")

        try:
            payload = {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                "temperature": 0.2, # Low temp for factual reasoning
                # "response_format": { "type": "json_object" } # Removed as it might cause issues with Qwen
            }
            
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://agriwise.app", 
                "X-Title": "AgriWise"
            }
            
            response = requests.post(self.api_url, headers=headers, json=payload, timeout=10)
            
            if not response.ok:
                 return self._fallback_response(f"API Error {response.status_code}: {response.text}")

            data = response.json()
            llm_content = data['choices'][0]['message']['content']
            
            # Debug: Print Raw LLM Content
            print(f"DEBUG RAW LLM: {llm_content}", file=os.sys.stderr)
            
            # Clean up potential markdown blocks
            llm_content = llm_content.strip()
            if llm_content.startswith("```json"):
                llm_content = llm_content[7:-3].strip()
            elif llm_content.startswith("```"):
                llm_content = llm_content[3:-3].strip()
            
            # 3. Parse Response (Expect JSON from LLM or structured text)
            # For robustness, we ask LLM to return JSON in system prompt
            try:
                parsed = json.loads(llm_content)
                
                # Validation: Ensure it's a dictionary
                if not isinstance(parsed, dict):
                     # Truncate content for logging if too long
                     preview = str(parsed)[:100]
                     raise ValueError(f"LLM returned {type(parsed)} instead of dict. Content: {preview}...")

                return {
                    "intent": parsed.get("intent", "general"),
                    "answer": parsed.get("answer", llm_content),
                    "evidence": parsed.get("evidence", []),
                    "confidence": "High"
                }
            except json.JSONDecodeError:
                # Fallback if LLM didn't return valid JSON
                return {
                    "intent": "general",
                    "answer": llm_content,
                    "evidence": ["Generated by AI"],
                    "confidence": "Medium"
                }

        except Exception as e:
            return self._fallback_response(f"LLM Error: {str(e)}")

    def _build_system_prompt(self, context: Dict[str, Any]) -> str:
        # Create a condensed string of the context
        context_str = json.dumps(context, indent=2)
        
        return f"""
You are AgriBrain, the Cognitive Interpreter for an advanced agronomy platform.
Your Role:
- You do NOT generate data. You interpret the verified data provided below.
- You explain complex agronomic models in simple, farmer-friendly language.
- You are helpful, professional, and concise.

Current Verified Context (Do not hallucinate outside this):
{context_str}

Instructions:
1. Analyze the user's query based ONLY on the provided context.
2. If the user asks "How are you" or "Status", summarize the system health (Trust Score) and mention 9-Layer Stack.
3. If the user asks about Yield/Risk, cite the specific numbers from context.
4. Output MUST be ONLY valid JSON with this structure (no markdown, no thinking):
{{
  "intent": "greeting" | "status" | "explain" | "general",
  "answer": "Your human-friendly response here...",
  "evidence": ["List of specific data points used, e.g. 'Risk Score: 45', 'Water Stress: 0.5'"]
}}
"""

    def _fallback_response(self, reasoning: str) -> Dict[str, Any]:
        return {
            "intent": "error",
            "answer": "I'm having trouble connecting to my cognitive center right now. Please check my connection.",
            "evidence": [reasoning],
            "confidence": "Low"
        }

# Singleton
qa_bot = QABot()
