
# Weather & Phenology Thresholds (Calibration Hook)

# WDP Constants
WETNESS_RAIN_DIVISOR = 25.0
WETNESS_DAYS_DIVISOR = 7.0
HEAT_PENALTY_DIVISOR = 14.0

FUNGAL_TEMP_OPTIMAL = 20.0
FUNGAL_TEMP_WIDTH = 12.0

BACTERIAL_TEMP_BASE = 18.0
BACTERIAL_TEMP_SCALE = 10.0

INSECT_DEGREE_BASE = 10.0
INSECT_DEGREE_SCALE = 15.0
INSECT_HEAT_OPTIMAL = 25.0

# RAS Logic Thresholds
PRESSURE_THRESHOLD_HIGH = 0.65
SPREAD_STRENGTH_STRONG = 0.60
DROP_MAGNITUDE_SIGNIFICANT = 0.20
