"""
Schemas for Drone Mission Orchestration.

Defines the semantic structures for drone capabilities, mission intent, 
and flight plans independent of any specific hardware API.
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any


class MissionType(str, Enum):
    """The seven core drone mission types for AgriWise."""
    FULL_PLOT_MAP = "full_plot_map"
    RAPID_SCOUT = "rapid_scout"
    ROW_AUDIT = "row_audit"
    WEED_MAP = "weed_map"
    ORCHARD_AUDIT = "orchard_audit"
    CONCERN_ZONE_COMMAND = "concern_zone_command"
    REFLY_WEAK_ZONES = "refly_weak_zones"  # V1.5B: Targeted re-fly of low-confidence zones


class FlightMode(str, Enum):
    """The dual-mode operational split."""
    MAPPING_MODE = "mapping_mode"              # High altitude, stitched ortho, structural extraction
    COMMAND_REVISIT_MODE = "command_revisit"   # Low altitude, raw frames, symptom/organ extraction


class CoveragePattern(str, Enum):
    """Flight path generation algorithms."""
    BOUSTROPHEDON = "boustrophedon"            # Standard lawnmower
    CONTOUR = "contour"                        # Terrain-following curves
    ROW_ALIGNED = "row_aligned"                # Lawnmower parallel to crop rows
    SPIRAL = "spiral"                          # Orbit for close inspection


@dataclass
class DroneCapabilityProfile:
    """Hardware abstraction for a standard commercial drone."""
    name: str
    camera_fov_horizontal_deg: float
    camera_fov_vertical_deg: float
    sensor_width_mm: float
    focal_length_mm: float
    image_width_px: int
    image_height_px: int
    
    # Flight dynamics
    max_flight_time_min: float
    max_speed_m_s: float
    min_safe_altitude_m: float
    max_safe_altitude_m: float
    
    # Safety margins
    return_home_reserve_pct: float = 20.0
    wind_resistance_m_s: float = 10.0
    
    def calculate_gsd(self, altitude_m: float) -> float:
        """Calculate Ground Sample Distance (cm/pixel) at given altitude."""
        # Simple pinhole model: GSD = (altitude * sensor_width) / (focal_length * image_width)
        # Convert altitude to mm, result in mm/pixel, then to cm/pixel
        gsd_mm = (altitude_m * 1000.0 * self.sensor_width_mm) / (self.focal_length_mm * self.image_width_px)
        return gsd_mm / 10.0

    def calculate_footprint(self, altitude_m: float) -> Tuple[float, float]:
        """Calculate the ground footprint (width_m, height_m) of a single image."""
        gsd_m = self.calculate_gsd(altitude_m) / 100.0
        return (self.image_width_px * gsd_m, self.image_height_px * gsd_m)


@dataclass
class MissionIntent:
    """The 'Why' and 'Where' generated by the Command Agent."""
    intent_id: str
    plot_id: str
    mission_type: MissionType
    flight_mode: FlightMode
    
    # Target geometry
    polygon_geojson: Dict[str, Any]       # GeoJSON polygon of the target area
    target_zone_id: Optional[str] = None  # If revisiting a specific anomaly zone
    
    # Constraints
    target_gsd_cm: float = 2.0
    required_overlap_pct: float = 70.0
    
    # Context
    trigger_source: str = "manual"        # e.g., "satellite_anomaly", "user_command"
    crop_type: Optional[str] = None


@dataclass
class Waypoint:
    """A single flight instruction."""
    lat: float
    lon: float
    alt_m: float
    action: str = "capture"               # "capture", "start_capture", "stop_capture", "hover"
    speed_m_s: Optional[float] = None


@dataclass
class FlightPlan:
    """The 'How' generated by the Planner."""
    plan_id: str
    intent_id: str
    drone_profile: str
    pattern: CoveragePattern
    
    waypoints: List[Waypoint]
    
    # Computed metrics
    estimated_flight_time_min: float
    estimated_image_count: int
    achieved_gsd_cm: float
    flight_altitude_m: float
    
    # Status
    is_feasible: bool = True
    infeasibility_reason: Optional[str] = None
